### PR TITLE
Test case

### PR DESCRIPTION
**Pull request by ippoippo**
I created test case for 042 numbers.

They are not being displayed correctly?

### CODE REVIEW

**Comment by iTakeshi** [comment]
Thank you for reporting this bug :+1: 

This is partly because the list of area codes was not properly sorted. Actually 1 of 2 new test cases you added was passed. See commit 9f04818
However, the other case is more confusing. The number "0422221111" can be parsed as 2 patterns. i.e. "042-222-1111" and "0422-22-1111". Surprisingly, BOTH the numbers are valid phone numbers and working in the real world (I googled for those numbers, and got existent companies for both cases!)

I don't have any solutions to handle this issue. Do you have an idea?

**Comment by ippoippo** [comment]
> BOTH the numbers are valid phone numbers and working in the real world
That can't be possible!?
If you dial 0422221111, which company would you get. It has to be deterministic. Which would mean the other one is incorrect.

If there is a ```0422-22-1111```, then that would take priority over ```042-222-1111```
Because there is a ```0422``` code, that would mean there cannot be any ```2xx-yyyy``` telephone numbers? Logically speaking.

This may be useful 
http://www.soumu.go.jp/main_sosiki/joho_tsusin/top/tel_number/q_and_a.html
http://www.soumu.go.jp/main_sosiki/joho_tsusin/top/tel_number/number_shitei.html

I may spend the weekend looking at this.

**Comment by iTakeshi** [comment]
> If you dial 0422221111, which company would you get. It has to be deterministic. Which would mean the other one is incorrect.

Year, I agree with you. I've carefully checked those numbers again, and "042-222-1111" appears to be expired.

So, by commit 9f04818, this gem works correctly according to the definition explained in the webpages you referred. Thanks for good references.
Then, please fix the spec that requires "0422221111" to be parsed as "042-222-1111". It has to be parsed as "0422-22-1111".
When updated, I'll merge this PR!

**Comment by ippoippo** [comment]
All looks good. Tests updated and the code is working how I expect it.
Feel free to merge in PR if you are happy.

**Comment by iTakeshi** [comment]
The new test cases look great! They hit the nail on the head.

But unfortunately, unnecessary change has been made in `.gitignore`.
Please revert the Rubymine specific change, and I'll merge this soon.

If you want to ignore `.idea` files in all repositories, I recommend to use global-gitignore.
See https://help.github.com/articles/ignoring-files/#create-a-global-gitignore

**Comment by ippoippo** [comment]
```.gitignore``` change undone.

**Comment by iTakeshi** [comment]
Great!

Thanks for your contribution :+1:

**Pull request merged**
